/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiTradeRouteImport } from './routes/api/trade'
import { Route as ApiPortfolioRouteImport } from './routes/api/portfolio'
import { Route as ApiNewsImpactRouteImport } from './routes/api/news-impact'
import { Route as ApiDailyPriceUpdateRouteImport } from './routes/api/daily-price-update'
import { Route as ApiPublicHooksUpdatePricesRouteImport } from './routes/api/public/hooks/update-prices'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradeRoute = ApiTradeRouteImport.update({
  id: '/api/trade',
  path: '/api/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioRoute = ApiPortfolioRouteImport.update({
  id: '/api/portfolio',
  path: '/api/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsImpactRoute = ApiNewsImpactRouteImport.update({
  id: '/api/news-impact',
  path: '/api/news-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyPriceUpdateRoute = ApiDailyPriceUpdateRouteImport.update({
  id: '/api/daily-price-update',
  path: '/api/daily-price-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUpdatePricesRoute =
  ApiPublicHooksUpdatePricesRouteImport.update({
    id: '/api/public/hooks/update-prices',
    path: '/api/public/hooks/update-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/api/daily-price-update': typeof ApiDailyPriceUpdateRoute
  '/api/news-impact': typeof ApiNewsImpactRoute
  '/api/portfolio': typeof ApiPortfolioRoute
  '/api/trade': typeof ApiTradeRoute
  '/p/$slug': typeof PSlugRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/api/daily-price-update': typeof ApiDailyPriceUpdateRoute
  '/api/news-impact': typeof ApiNewsImpactRoute
  '/api/portfolio': typeof ApiPortfolioRoute
  '/api/trade': typeof ApiTradeRoute
  '/p/$slug': typeof PSlugRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/api/daily-price-update': typeof ApiDailyPriceUpdateRoute
  '/api/news-impact': typeof ApiNewsImpactRoute
  '/api/portfolio': typeof ApiPortfolioRoute
  '/api/trade': typeof ApiTradeRoute
  '/p/$slug': typeof PSlugRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/portfolio'
    | '/api/daily-price-update'
    | '/api/news-impact'
    | '/api/portfolio'
    | '/api/trade'
    | '/p/$slug'
    | '/api/public/hooks/update-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/portfolio'
    | '/api/daily-price-update'
    | '/api/news-impact'
    | '/api/portfolio'
    | '/api/trade'
    | '/p/$slug'
    | '/api/public/hooks/update-prices'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/portfolio'
    | '/api/daily-price-update'
    | '/api/news-impact'
    | '/api/portfolio'
    | '/api/trade'
    | '/p/$slug'
    | '/api/public/hooks/update-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  ApiDailyPriceUpdateRoute: typeof ApiDailyPriceUpdateRoute
  ApiNewsImpactRoute: typeof ApiNewsImpactRoute
  ApiPortfolioRoute: typeof ApiPortfolioRoute
  ApiTradeRoute: typeof ApiTradeRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicHooksUpdatePricesRoute: typeof ApiPublicHooksUpdatePricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trade': {
      id: '/api/trade'
      path: '/api/trade'
      fullPath: '/api/trade'
      preLoaderRoute: typeof ApiTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio': {
      id: '/api/portfolio'
      path: '/api/portfolio'
      fullPath: '/api/portfolio'
      preLoaderRoute: typeof ApiPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news-impact': {
      id: '/api/news-impact'
      path: '/api/news-impact'
      fullPath: '/api/news-impact'
      preLoaderRoute: typeof ApiNewsImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-price-update': {
      id: '/api/daily-price-update'
      path: '/api/daily-price-update'
      fullPath: '/api/daily-price-update'
      preLoaderRoute: typeof ApiDailyPriceUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/update-prices': {
      id: '/api/public/hooks/update-prices'
      path: '/api/public/hooks/update-prices'
      fullPath: '/api/public/hooks/update-prices'
      preLoaderRoute: typeof ApiPublicHooksUpdatePricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  ApiDailyPriceUpdateRoute: ApiDailyPriceUpdateRoute,
  ApiNewsImpactRoute: ApiNewsImpactRoute,
  ApiPortfolioRoute: ApiPortfolioRoute,
  ApiTradeRoute: ApiTradeRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicHooksUpdatePricesRoute: ApiPublicHooksUpdatePricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
